config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  direct :rails_blob do |blob|
    route_for(:rails_service_blob, blob.signed_id, blob.filename)
  end
  
  get 'up' => 'rails/health#show', as: :rails_health_check

  # It should be before users controller to avoid conflicts
  devise_for :users

  root 'dashboard#index'

  resources :users
  resources :clients
  resources :agents
  resources :components
  resources :products do
    resources :components, except: %i[index show], controller: 'product_components'
    resources :product_components do
      patch :update_quantity, on: :member
    end
  end
  resources :orders do
    resources :versions, except: %i[index], controller: 'order_versions' do
      patch :mark_as_final, on: :member
      post :duplicate, on: :member
    end
    delete :remove_file, on: :member
    member do
      get :quotation_preview
      patch :add_custom_code
      get :components_order
      post :duplicate
    end
    resources :components_orders, only: [:index] do
      get :print, on: :collection
      collection do
        post :send_email_to_supplier
      end
    end
    resource :installation_report, only: %i[create show destroy] do
      resources :installation_report_items, only: [:update] do
        delete :purge_photo, on: :member
        patch :edit_photo, on: :member
      end
    end
    resource :defect_list, only: %i[create show destroy] do
      resources :defect_list_items, only: %i[create update destroy] do
        delete :purge_photo, on: :member
        patch :edit_photo, on: :member
      end
    end

  end 
  resources :transactions do
    member do
      delete :destroy_attachment
    end
  end

  resources :balances, only: [:index] do
    collection do
      get :print
    end
  end
  resources :suppliers, except: [:show]
  
  resources :stock_movements, only: %i[index new create edit update destroy] do
    collection do
      get :summary
    end
  end

 
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  





  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

# == Route Map
#
#                            Prefix Verb   URI Pattern                                                                                       Controller#Action
#                                          /assets                                                                                           Propshaft::Server
#                rails_health_check GET    /up(.:format)                                                                                     rails/health#show
#                  new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
#                      user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
#              destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
#                 new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
#                edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
#                     user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
#                                   PUT    /users/password(.:format)                                                                         devise/passwords#update
#                                   POST   /users/password(.:format)                                                                         devise/passwords#create
#                              root GET    /                                                                                                 dashboard#index
#                             users GET    /users(.:format)                                                                                  users#index
#                                   POST   /users(.:format)                                                                                  users#create
#                          new_user GET    /users/new(.:format)                                                                              users#new
#                         edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
#                              user GET    /users/:id(.:format)                                                                              users#show
#                                   PATCH  /users/:id(.:format)                                                                              users#update
#                                   PUT    /users/:id(.:format)                                                                              users#update
#                                   DELETE /users/:id(.:format)                                                                              users#destroy
#                           clients GET    /clients(.:format)                                                                                clients#index
#                                   POST   /clients(.:format)                                                                                clients#create
#                        new_client GET    /clients/new(.:format)                                                                            clients#new
#                       edit_client GET    /clients/:id/edit(.:format)                                                                       clients#edit
#                            client GET    /clients/:id(.:format)                                                                            clients#show
#                                   PATCH  /clients/:id(.:format)                                                                            clients#update
#                                   PUT    /clients/:id(.:format)                                                                            clients#update
#                                   DELETE /clients/:id(.:format)                                                                            clients#destroy
#                            agents GET    /agents(.:format)                                                                                 agents#index
#                                   POST   /agents(.:format)                                                                                 agents#create
#                         new_agent GET    /agents/new(.:format)                                                                             agents#new
#                        edit_agent GET    /agents/:id/edit(.:format)                                                                        agents#edit
#                             agent GET    /agents/:id(.:format)                                                                             agents#show
#                                   PATCH  /agents/:id(.:format)                                                                             agents#update
#                                   PUT    /agents/:id(.:format)                                                                             agents#update
#                                   DELETE /agents/:id(.:format)                                                                             agents#destroy
#                        components GET    /components(.:format)                                                                             components#index
#                                   POST   /components(.:format)                                                                             components#create
#                     new_component GET    /components/new(.:format)                                                                         components#new
#                    edit_component GET    /components/:id/edit(.:format)                                                                    components#edit
#                         component GET    /components/:id(.:format)                                                                         components#show
#                                   PATCH  /components/:id(.:format)                                                                         components#update
#                                   PUT    /components/:id(.:format)                                                                         components#update
#                                   DELETE /components/:id(.:format)                                                                         components#destroy
#                product_components GET    /products/:product_id/product_components(.:format)                                                product_components#index
#                                   POST   /products/:product_id/product_components(.:format)                                                product_components#create
#             new_product_component GET    /products/:product_id/product_components/new(.:format)                                            product_components#new
#            edit_product_component GET    /products/:product_id/product_components/:id/edit(.:format)                                       product_components#edit

app/controllers/order_versions_controller.rb
# frozen_string_literal: true

class OrderVersionsController < ApplicationController
  before_action :set_order
  before_action :set_order_version, except: %i[new create]

  def show; end

  # GET /order_versions/new
  def new
    @order_version = OrderVersion.new
  end

  # GET /order_versions/1/edit
  def edit; end

  # POST /order_versions
  def create
    @order_version = OrderVersion.new(order_version_params)
    @order_version.order = @order
    @order_version.company = @order.company

    if @order_version.save
      redirect_to @order, notice: 'Order version was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /order_versions/1
  def update
    was_final = @order_version.final_version_before_last_save

    if @order_version.update(order_version_params)
      if @order_version.final_version && !was_final
        @order.order_versions.where.not(id: @order_version.id).find_each do |ov|
          ov.final_version = false
          ov.save!
        end
      end

      # Update product prices and order total
      @order_version.products.each(&:update_price)
      @order_version.update_total_amount

      redirect_to @order, notice: 'Order version was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def duplicate
    new_version = OrderDuplicator.duplicate_version(@order_version)
    redirect_to edit_order_version_path(@order, new_version), notice: 'Version copied'
  end

  # DELETE /order_versions/1
  def destroy
    @order_version.destroy!
    redirect_to @order, notice: 'Order version was successfully destroyed.', status: :see_other
  end

  def mark_as_final
    @order_version.update(final_version: true)
    redirect_to order_path(@order), notice: 'Order version was successfully marked as final.'
  end

  private

  def set_order
    @order = current_company.orders.find(params[:order_id] || params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_order_version
    @order_version = @order.order_versions.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_version_params
    params.expect(order_version: %i[agent_comm profit version_note final_version note_for_client])
  end
end

app/helpers/order_versions_helper.rb
# frozen_string_literal: true

module OrderVersionsHelper
  def order_version_tabs(order, order_versions)
    buttons = order_versions_buttons(order, order_versions)

    tabs = order_versions_tabs(order_versions)

    content_tag(:div, safe_join(buttons), class: 'tabs__list mbe-4 overflow-y-auto',
                                          data: { action: 'keydown.left->tabs#prev keydown.right->tabs#next' },
                                          role: 'tablist') + safe_join(tabs)
  end

  def new_product(order_version)
    Product.new(order_version: order_version)
  end

  private

  def order_versions_buttons(order, order_versions)
    new_version_button = link_to '➕ New Version', new_order_version_path(order.id),
                                 class: 'btn tabs__button'

    total_versions = order_versions.size

    version_buttons = order_versions.map.with_index do |order_version, index|
      version_number = total_versions - index
      date_label = "V#{version_number} #{order_version.created_at.strftime('%d-%m-%Y')}"

      tag.button(date_label,
                 type: 'button',
                 id: "trigger_#{order_version.id}",
                 class: 'btn tabs__button',
                 data: { 'tabs-target': 'button', action: 'tabs#select' },
                 role: 'tab',
                 style: (order_version.final_version? ? '--color-text: #2dd63b' : '').to_s,
                 'aria-controls': dom_id(order_version))
    end

    [new_version_button] + version_buttons
  end

  def order_versions_tabs(order_versions)
    order_versions.map do |order_version|
      turbo_frame_tag order_version, src: order_version_path(order_version.order_id, order_version.id),
                                     data: { 'tabs-target': 'tab' },
                                     role: 'tabpanel',
                                     'aria-labelledby': "trigger_#{order_version.id}",
                                     loading: 'lazy' do
        <<~HTML.html_safe # rubocop:disable Rails/OutputSafety
          <div class="flex items-center gap">
            <div class="flex flex-col gap w-full">
              <div class="skeleton" style="height: var(--size-4); width: 800px;"></div>
              <div class="skeleton" style="height: var(--size-4); width: 800px;"></div>
              <div class="skeleton" style="height: var(--size-4); width: 800px;"></div>
              <div class="skeleton" style="height: var(--size-4); width: 800px;"></div>
              <div class="skeleton" style="height: var(--size-4); width: 800px;"></div>
              <div class="skeleton" style="height: var(--size-4); width: 800px;"></div>
            </div>
          </div>
        HTML
      end
    end
  end
end

app/views/order_versions/_form.html.erb
  <%= form_with(model: order_version, url: order_version.persisted? ? order_version_path(@order, order_version) : order_versions_path(@order), html: { contents: true }) do |form| %>
  <% if order_version.errors.any? %>
    <div class="alert alert--negative flex flex-col gap-half mbe-4" role="alert">
      <h2 class="font-medium leading-none"><%= pluralize(order_version.errors.count, "error") %> prohibited this order_version from being saved:</h2>
      <ul class="text-sm mis-3" style="list-style: disc">
        <% order_version.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex flex-col items-start gap-half mbe-4">
    <%= form.label :profit, "Profit, %", class: "text-sm font-medium leading-none" %>
    <%= form.text_field :profit, class: "input" %>
  </div>
  <div class="flex flex-col items-start gap-half mbe-4">
    <%= form.label :agent_comm, "Agent, %", class: "text-sm font-medium leading-none" %>
    <%= form.text_field :agent_comm, class: "input" %>
  </div>
  <div class="flex flex-col items-start gap-half mbe-4">
    <%= form.label :version_note, class: "text-sm font-medium leading-none" %>
    <%= form.text_field :version_note, class: "input" %>
  </div>
  <div class="flex flex-col items-start gap-half mbe-4">
    <%= form.label :note_for_client, class: "text-sm font-medium leading-none" %>
    <%= form.text_field :note_for_client, class: "input" %>
    <p style="color: var(--color-negative);">Client will see this note!</p>
  </div>
  <div class="flex items-center gap  mbe-4">
    <%= form.check_box :final_version, class: "checkbox" %>
    <%= form.label :final_version, class: "text-sm font-medium" %>
  </div>
  <div class="inline-flex items-center justify-between mbs-2 mie-1 gap">
    <%= link_to "Back", @order, class: "btn" %>
    <%= button_tag tag.span(order_version.persisted? ? "Update Version" : "Create Version"), class: "btn btn--primary btn--loading" %>
  </div>
<% end %>

app/views/order_versions/_new_product.html.erb
<div class="flex items-center gap">
  <%= link_to "Create new", new_product_path(order_version_id: order_version.id), class: "btn btn--secondary" %>
  <div>or</div>
  <%= link_to "Select from template", new_product_path(order_version_id: order_version.id, from_template: true), class: "btn btn--primary" %>
</div>

app/views/order_versions/_order_version.html.erb
<%= turbo_stream_from(order_version) %> 
<p>Profit: <%= order_version.profit %> %</p>
<p>Agent: <%= order_version.agent_comm %> %</p>
<p>Total Amount: <%= order_version.total_amount.format %></p>
<p>Version Note: <%= order_version.version_note %></p>
<p>Note for client: <%= order_version.note_for_client.presence || "—" %></p>
<p>Final Version: <%= order_version.final_version ? 'Yes' : 'No' %></p>
<div class="flex items-center justify-end gap">
  <%= link_to "Make final", mark_as_final_order_version_path(order_version.order_id, order_version), class: "btn", data: { turbo_method: :patch, turbo_frame: "_top" } unless order_version.final_version %>
  <%= button_to 'Copy', duplicate_order_version_path(order_version.order_id, order_version),
               method: :post, class: "btn", data: { turbo_frame: "_top" } %>
  <%= link_to 'Edit', edit_order_version_path(order_version.order_id, order_version), class: "btn", data: {turbo_frame: "_top"} %>
  <%= link_to 'Delete', order_version_path(order_version.order_id, order_version), class: "btn", data: { turbo_method: :delete, turbo_confirm: "Are you absolutely sure?",turbo_frame: "_top" } %>
</div>
<div class="mbs-2">
  <div class="flex items-center justify-between w-full gap mbe-2">
    <h2 class="font-bold text-lg">Products included in order</h2>
    <div data-controller="dialog">
      <button type="button" class="btn" data-action="dialog#showModal">Add Product</button>
      <dialog class="dialog" data-dialog-target="menu" aria-label="Edit profile">
        <button type="button" class="btn btn--plain dialog__close" data-action="click->dialog#close">
          <%= image_tag "x.svg", size: 16, aria: { hidden: true } %>
          <span class="sr-only">Close</span>
        </button>
        <div class="dialog__content">
          <%= turbo_frame_tag(new_product(order_version), order_version.id) do %>
            <h1 class="font-bold text-4xl mbe-4">New product</h1>
            <%= render "order_versions/new_product", order_version: order_version %>
          <% end %>
        </div>
      </dialog>
    </div>
  </div>
  <div class="overflow-x-auto w-full">
  <table class="table  min-w-[1500px]">
    <thead>
      <tr>
        <th>#</th>
        <th>Image</th>
        <th>Name</th>
        <th>Qty</th>
        <th style='white-space: nowrap;'>W, m</th>
        <th style='white-space: nowrap;'>H, m</th>
        <th style='white-space: nowrap;'>Area, m²</th>
        <th>Aluminum</th>
        <th>Glass</th>
        <th>Other</th>
        <th>Price</th>
        <th>Nett</th>
        <th>Profit</th>
        <th>Amount</th>
        <th>Nett total</th>        
        <th>Profit total</th>
        <th>Total</th>
        <th></th>
      </tr>
    </thead>
    <tbody id="<%= dom_id(order_version, 'products') %>">
      <%#= render partial: "products/product_order_row", collection: order_version.products.with_image_variants, as: :product, cached: true %>
      <% order_version.products.with_image_variants.each_with_index do |product, index| %>
        <%= render partial: "products/product_order_row", locals: { product: product, index: index } %>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="15">Grand Totals:</td>
        <td class="text-end">
          <%= order_version.total_profit_amount.format %>
        </td>
        <td class="text-end">
          <%= order_version.total_amount.format %>
        </td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  </div>
</div>

app/views/order_versions/edit.html.erb
<% content_for :title, "Editing order version" %>

<h1 class="font-bold text-4xl mbe-4">Editing order version</h1>

<%= render "form", order: @order, order_version: @order_version %>

app/views/order_versions/new.html.erb
<% content_for :title, "New order version" %>

<h1 class="font-bold text-4xl mbe-4">New order version</h1>

<%= render "form", order_version: @order_version %>

app/views/order_versions/show.html.erb
<% content_for :title, "Order ##{@order_version.order_id} Version #{@order_version.created_at}" %>
<%= turbo_frame_tag @order_version, class: "flex flex-col gap" do %>
  <%= render "order_versions/order_version", order_version: @order_version %>
<% end %>