config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  direct :rails_blob do |blob|
    route_for(:rails_service_blob, blob.signed_id, blob.filename)
  end
  
  get 'up' => 'rails/health#show', as: :rails_health_check

  # It should be before users controller to avoid conflicts
  devise_for :users

  root 'dashboard#index'

  resources :users
  resources :clients
  resources :agents
  resources :components
  resources :products do
    resources :components, except: %i[index show], controller: 'product_components'
    resources :product_components do
      patch :update_quantity, on: :member
    end
  end
  resources :orders do
    resources :versions, except: %i[index], controller: 'order_versions' do
      patch :mark_as_final, on: :member
      post :duplicate, on: :member
    end
    delete :remove_file, on: :member
    member do
      get :quotation_preview
      patch :add_custom_code
      get :components_order
      post :duplicate
    end
    resources :components_orders, only: [:index] do
      get :print, on: :collection
      collection do
        post :send_email_to_supplier
      end
    end
    resource :installation_report, only: %i[create show destroy] do
      resources :installation_report_items, only: [:update] do
        delete :purge_photo, on: :member
        patch :edit_photo, on: :member
      end
    end
    resource :defect_list, only: %i[create show destroy] do
      resources :defect_list_items, only: %i[create update destroy] do
        delete :purge_photo, on: :member
        patch :edit_photo, on: :member
      end
    end

  end 
  resources :transactions do
    member do
      delete :destroy_attachment
    end
  end

  resources :balances, only: [:index] do
    collection do
      get :print
    end
  end
  resources :suppliers, except: [:show]
  
  resources :stock_movements, only: %i[index new create edit update destroy] do
    collection do
      get :summary
    end
  end

 
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  





  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

# == Route Map
#
#                            Prefix Verb   URI Pattern                                                                                       Controller#Action
#                                          /assets                                                                                           Propshaft::Server
#                rails_health_check GET    /up(.:format)                                                                                     rails/health#show
#                  new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
#                      user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
#              destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
#                 new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
#                edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
#                     user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
#                                   PUT    /users/password(.:format)                                                                         devise/passwords#update
#                                   POST   /users/password(.:format)                                                                         devise/passwords#create
#                              root GET    /                                                                                                 dashboard#index
#                             users GET    /users(.:format)                                                                                  users#index
#                                   POST   /users(.:format)                                                                                  users#create
#                          new_user GET    /users/new(.:format)                                                                              users#new
#                         edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
#                              user GET    /users/:id(.:format)                                                                              users#show
#                                   PATCH  /users/:id(.:format)                                                                              users#update
#                                   PUT    /users/:id(.:format)                                                                              users#update
#                                   DELETE /users/:id(.:format)                                                                              users#destroy
#                           clients GET    /clients(.:format)                                                                                clients#index
#                                   POST   /clients(.:format)                                                                                clients#create
#                        new_client GET    /clients/new(.:format)                                                                            clients#new
#                       edit_client GET    /clients/:id/edit(.:format)                                                                       clients#edit
#                            client GET    /clients/:id(.:format)                                                                            clients#show
#                                   PATCH  /clients/:id(.:format)                                                                            clients#update
#                                   PUT    /clients/:id(.:format)                                                                            clients#update
#                                   DELETE /clients/:id(.:format)                                                                            clients#destroy
#                            agents GET    /agents(.:format)                                                                                 agents#index
#                                   POST   /agents(.:format)                                                                                 agents#create
#                         new_agent GET    /agents/new(.:format)                                                                             agents#new
#                        edit_agent GET    /agents/:id/edit(.:format)                                                                        agents#edit
#                             agent GET    /agents/:id(.:format)                                                                             agents#show
#                                   PATCH  /agents/:id(.:format)                                                                             agents#update
#                                   PUT    /agents/:id(.:format)                                                                             agents#update
#                                   DELETE /agents/:id(.:format)                                                                             agents#destroy
#                        components GET    /components(.:format)                                                                             components#index
#                                   POST   /components(.:format)                                                                             components#create
#                     new_component GET    /components/new(.:format)                                                                         components#new
#                    edit_component GET    /components/:id/edit(.:format)                                                                    components#edit
#                         component GET    /components/:id(.:format)                                                                         components#show
#                                   PATCH  /components/:id(.:format)                                                                         components#update
#                                   PUT    /components/:id(.:format)                                                                         components#update
#                                   DELETE /components/:id(.:format)                                                                         components#destroy
#                product_components GET    /products/:product_id/product_components(.:format)                                                product_components#index
#                                   POST   /products/:product_id/product_components(.:format)                                                product_components#create
#             new_product_component GET    /products/:product_id/product_components/new(.:format)                                            product_components#new
#            edit_product_component GET    /products/:product_id/product_components/:id/edit(.:format)                                       product_components#edit

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[edit update destroy]

  def index
    @search = Transaction.ransack(params[:q])
    @transactions = @search.result.includes(:order, :client, :agent).order(date: :desc)
    @pagy, @transactions = pagy(@transactions)
  end

  def new
    @transaction = Transaction.new(date: Time.zone.today)
  end

  def edit
    # @transaction = Transaction.find(params[:id])
    redirect_to balances_path, alert: 'Editing not allowed after 7 days.' unless @transaction.editable?
  end

  def create
    @transaction = current_company.transactions.new(transaction_params)

    if @transaction.save
      if params[:transaction][:files].present?
        params[:transaction][:files].each do |file|
          @transaction.files.attach(file)
        end
      end

      redirect_to balances_path, notice: 'Transaction created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    return redirect_to balances_path, alert: 'Editing not allowed after 7 days.' unless @transaction.editable?

    if @transaction.update(transaction_params)
      # Добавить новые файлы, если есть
      if params[:transaction][:files].present?
        params[:transaction][:files].each do |file|
          @transaction.files.attach(file)
        end
      end

      redirect_to balances_path, notice: 'Transaction updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @transaction = Transaction.find(params[:id])
    redirect_to balances_path, alert: 'Editing not allowed after 7 days.' and return unless @transaction.editable?

    @transaction.destroy
    redirect_to balances_path, notice: 'Transaction was successfully deleted.', status: :see_other
  end

  def destroy_attachment
    transaction = Transaction.find(params[:id])
    file = transaction.files.find(params[:file_id])
    file.purge_later

    redirect_back fallback_location: edit_transaction_path(transaction), notice: 'Файл удалён'
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.expect(
      transaction: %i[
        date
        description
        amount
        type_id
        order_id
        agent_id
        client_id
        hidden
        only_for_accounting
      ]
    )
  end
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
  def format_money(value)
    Money.from_amount(value).format
  end
end

app/views/transactions/_form.html.erb
<% if transaction.errors.any? %>
  <div class="bg-red-100 text-red-700 p-4 rounded">
    <p class="font-semibold">Ошибки:</p>
    <ul class="list-disc list-inside">
      <% transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: transaction, local: true, html: { multipart: true }, class: "flex flex-col gap-6" do |f| %>
  <div class="flex flex-col gap-2">
    <%= f.label :date, "Date", class: "label" %>
    <%= f.date_field :date, class: "input" %>
  </div>

  <div class="flex flex-col gap-2">
    <%= f.label :description, "Description", class: "label" %>
    <%= f.text_field :description, class: "input" %>
  </div>

  <div class="flex flex-col gap-2">
    <%= f.label :amount, "Amount", class: "label" %>
    <%= f.number_field :amount, step: 0.01, class: "input" %>
  </div>

  <div class="flex flex-col gap-2">
    <%= f.label :type_id, "Type", class: "label" %>
    <%= f.select :type_id,
      Transaction.type_ids.keys.map { |key| [key.humanize, key] },
      { include_blank: true },
      class: "input" %>
  </div>

  <div class="flex flex-col gap-2">
    <%= f.label :order_id, "Project", class: "label" %>
    <%= f.collection_select :order_id, current_company.orders, :id, :name,
      { include_blank: true },
      class: "input" %>
  </div>

  <div class="flex flex-col gap-2">
    <%= f.label :agent_id, "Agent", class: "label" %>
    <%= f.collection_select :agent_id, current_company.agents, :id, :name,
      { include_blank: true },
      class: "input" %>
  </div>

  <div class="flex flex-col gap-2">
    <%= f.label :client_id, "Client", class: "label" %>
    <%= f.collection_select :client_id, current_company.clients, :id, :name,
      { include_blank: true },
      class: "input" %>
  </div>

  <div class="flex flex-col gap-2">
    <%= f.label :files, "Attach files", class: "label" %>
    <%= f.file_field :files, multiple: true, class: "input", direct_upload: true %>

    <% if transaction.files.attached? %>
      <ul class="text-sm space-y-1 mt-2">
        <% transaction.files.each do |file| %>
          <li class="flex items-center justify-between">
            <%= link_to file.filename.to_s, rails_blob_path(file, disposition: "attachment"), target: "_blank" %>
            <%= link_to "❌", destroy_attachment_transaction_path(transaction, attachment_id: file.id),
              method: :delete,
              data: { confirm: "Remove file #{file.filename}?" },
              class: "text-red-500 text-xs" %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= f.check_box :hidden %>
    <%= f.label :hidden, "Hidden" %>
  </div>

  <div>
    <%= f.check_box :only_for_accounting %>
    <%= f.label :only_for_accounting, "Only for accounting" %>
  </div>

  <%#= f.submit "Create Transaction", class: "btn btn--primary", data: { disable_with: "Saving..." } %>
<%= f.submit transaction.persisted? ? "Update Transaction" : "Create Transaction",
  class: "btn btn--primary",
  data: { disable_with: "Saving..." } %>
<% end %>

app/views/transactions/edit.html.erb
<% content_for :title, "Edit Transaction" %>

<div class="container max-w-xl">
  <h1 class="text-2xl font-bold mbe-4">New Transaction</h1>
  <%= render "form", transaction: @transaction %>
</div>

app/views/transactions/index.html.erb
<% content_for :title, "Transactions" %>

<div class="container flex flex-col gap-4">
  <div class="flex items-center justify-between">
    <h1 class="text-3xl font-bold">Transactions</h1>
    <%= link_to "New transaction", new_transaction_path, class: "btn btn--primary" %>
  </div>

  <%= search_form_for @search, url: transactions_path, method: :get, class: "flex flex-wrap gap-2 items-end", data: { controller: "form" } do |f| %>
    <%= f.date_field :date_gteq, placeholder: "From", class: "input", data: { action: "change->form#submit" } %>
    <%= f.date_field :date_lteq, placeholder: "To", class: "input", data: { action: "change->form#submit" } %>

    <%= f.select :type_id_eq, Transaction.type_ids.invert, { include_blank: "Any type" }, class: "input", data: { action: "change->form#submit" } %>
    <%= f.collection_select :order_id_eq, current_company.orders, :id, :name, { include_blank: "Any project" }, class: "input", data: { action: "change->form#submit" } %>
    <%= f.collection_select :agent_id_eq, current_company.agents, :id, :name, { include_blank: "Any agent" }, class: "input", data: { action: "change->form#submit" } %>
    <%= f.collection_select :client_id_eq, current_company.clients, :id, :name, { include_blank: "Any client" }, class: "input", data: { action: "change->form#submit" } %>
  <% end %>

  <div class="relative overflow-x-auto border rounded-lg">
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Description</th>
          <th>Type</th>
          <th>Amount</th>
          <th>Project</th>
          <th>Agent</th>
          <th>Client</th>
        </tr>
      </thead>
      <tbody>
        <% @transactions.each do |t| %>
          <tr>
            <td><%= t.date.strftime("%d.%m.%y") %></td>
            <td><%= t.description %></td>
            <td><%= t.type_id.humanize %></td>
            <td class="<%= t.amount.positive? ? 'text-green-600' : 'text-red-600' %>">
              <%= number_to_currency(t.amount) %>
            </td>
            <td><%= t.order&.name %></td>
            <td><%= t.agent&.name %></td>
            <td><%= t.client&.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="mt-4">
    <%= pagy_nav(@pagy) %>
  </div>
</div>

app/views/transactions/new.html.erb
<% content_for :title, "New Transaction" %>

<div class="container max-w-xl">
  <h1 class="text-2xl font-bold mbe-4">New Transaction</h1>
  <%= render "form", transaction: @transaction %>
</div>