config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  direct :rails_blob do |blob|
    route_for(:rails_service_blob, blob.signed_id, blob.filename)
  end
  
  get 'up' => 'rails/health#show', as: :rails_health_check

  # It should be before users controller to avoid conflicts
  devise_for :users

  root 'dashboard#index'

  resources :users
  resources :clients
  resources :agents
  resources :components
  resources :products do
    resources :components, except: %i[index show], controller: 'product_components'
    resources :product_components do
      patch :update_quantity, on: :member
    end
  end
  resources :orders do
    resources :versions, except: %i[index], controller: 'order_versions' do
      patch :mark_as_final, on: :member
      post :duplicate, on: :member
    end
    delete :remove_file, on: :member
    member do
      get :quotation_preview
      patch :add_custom_code
      get :components_order
      post :duplicate
    end
    resources :components_orders, only: [:index] do
      get :print, on: :collection
      collection do
        post :send_email_to_supplier
      end
    end
    resource :installation_report, only: %i[create show destroy] do
      resources :installation_report_items, only: [:update] do
        delete :purge_photo, on: :member
        patch :edit_photo, on: :member
      end
    end
    resource :defect_list, only: %i[create show destroy] do
      resources :defect_list_items, only: %i[create update destroy] do
        delete :purge_photo, on: :member
        patch :edit_photo, on: :member
      end
    end

  end 
  resources :transactions do
    member do
      delete :destroy_attachment
    end
  end

  resources :balances, only: [:index] do
    collection do
      get :print
    end
  end
  resources :suppliers, except: [:show]
  
  resources :stock_movements, only: %i[index new create edit update destroy] do
    collection do
      get :summary
    end
  end

 
  
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  





  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

# == Route Map
#
#                            Prefix Verb   URI Pattern                                                                                       Controller#Action
#                                          /assets                                                                                           Propshaft::Server
#                rails_health_check GET    /up(.:format)                                                                                     rails/health#show
#                  new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
#                      user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
#              destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
#                 new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
#                edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
#                     user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
#                                   PUT    /users/password(.:format)                                                                         devise/passwords#update
#                                   POST   /users/password(.:format)                                                                         devise/passwords#create
#                              root GET    /                                                                                                 dashboard#index
#                             users GET    /users(.:format)                                                                                  users#index
#                                   POST   /users(.:format)                                                                                  users#create
#                          new_user GET    /users/new(.:format)                                                                              users#new
#                         edit_user GET    /users/:id/edit(.:format)                                                                         users#edit
#                              user GET    /users/:id(.:format)                                                                              users#show
#                                   PATCH  /users/:id(.:format)                                                                              users#update
#                                   PUT    /users/:id(.:format)                                                                              users#update
#                                   DELETE /users/:id(.:format)                                                                              users#destroy
#                           clients GET    /clients(.:format)                                                                                clients#index
#                                   POST   /clients(.:format)                                                                                clients#create
#                        new_client GET    /clients/new(.:format)                                                                            clients#new
#                       edit_client GET    /clients/:id/edit(.:format)                                                                       clients#edit
#                            client GET    /clients/:id(.:format)                                                                            clients#show
#                                   PATCH  /clients/:id(.:format)                                                                            clients#update
#                                   PUT    /clients/:id(.:format)                                                                            clients#update
#                                   DELETE /clients/:id(.:format)                                                                            clients#destroy
#                            agents GET    /agents(.:format)                                                                                 agents#index
#                                   POST   /agents(.:format)                                                                                 agents#create
#                         new_agent GET    /agents/new(.:format)                                                                             agents#new
#                        edit_agent GET    /agents/:id/edit(.:format)                                                                        agents#edit
#                             agent GET    /agents/:id(.:format)                                                                             agents#show
#                                   PATCH  /agents/:id(.:format)                                                                             agents#update
#                                   PUT    /agents/:id(.:format)                                                                             agents#update
#                                   DELETE /agents/:id(.:format)                                                                             agents#destroy
#                        components GET    /components(.:format)                                                                             components#index
#                                   POST   /components(.:format)                                                                             components#create
#                     new_component GET    /components/new(.:format)                                                                         components#new
#                    edit_component GET    /components/:id/edit(.:format)                                                                    components#edit
#                         component GET    /components/:id(.:format)                                                                         components#show
#                                   PATCH  /components/:id(.:format)                                                                         components#update
#                                   PUT    /components/:id(.:format)                                                                         components#update
#                                   DELETE /components/:id(.:format)                                                                         components#destroy
#                product_components GET    /products/:product_id/product_components(.:format)                                                product_components#index
#                                   POST   /products/:product_id/product_components(.:format)                                                product_components#create
#             new_product_component GET    /products/:product_id/product_components/new(.:format)                                            product_components#new
#            edit_product_component GET    /products/:product_id/product_components/:id/edit(.:format)                                       product_components#edit

app/models/product.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: products
#
#  id               :integer          not null, primary key
#  comment          :string
#  height           :integer          default(0), not null
#  name             :string           not null
#  price_cents      :integer          default(0), not null
#  quantity         :integer
#  width            :integer          default(0), not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  company_id       :integer          not null
#  order_version_id :integer
#
# Indexes
#
#  index_products_on_company_id        (company_id)
#  index_products_on_order_version_id  (order_version_id)
#
# Foreign Keys
#
#  company_id        (company_id => companies.id)
#  order_version_id  (order_version_id => order_versions.id)
#
class Product < ApplicationRecord
  include PriceCalculations

  attribute :from_template, :boolean, default: false
  attribute :template_id, :integer

  delegate :currency, to: :company, allow_nil: true

  monetize :price_cents, with_model_currency: :currency
  monetize :aluminum_price_cents, with_model_currency: :currency
  monetize :glass_price_cents, with_model_currency: :currency
  monetize :other_price_cents, with_model_currency: :currency
  monetize :nett_price_cents, with_model_currency: :currency
  monetize :profit_amount_cents, with_model_currency: :currency
  monetize :price_with_profit_cents, with_model_currency: :currency
  monetize :total_nett_price_cents, with_model_currency: :currency
  monetize :total_profit_amount_cents, with_model_currency: :currency
  monetize :total_price_with_profit_cents, with_model_currency: :currency

  belongs_to :company
  belongs_to :order_version, optional: true
  has_many :product_components, dependent: :destroy
  has_many :components, through: :product_components
  has_many :installation_report_items, dependent: :destroy
  has_many :defect_list_items, dependent: :destroy
  has_one_attached :image, dependent: :purge

  validates :name, :width, :height, presence: true
  validates :width, :height, numericality: { greater_than_or_equal_to: 0 }

  before_validation :copy_template, if: -> { from_template? }, on: :create
  after_destroy :update_order_version_total_amount, if: -> { order_version.present? }
  after_save :recalculate_product_components_amount, if: -> { saved_change_to_width? || saved_change_to_height? }
  before_commit :update_order_version_total_amount, if: lambda {
    order_version.present? && (saved_change_to_price_cents? || saved_change_to_quantity?)
  }, on: %i[update create]

  scope :templates, -> { where(order_version: nil) }
  scope :with_image_variants, -> { includes(image_attachment: [blob: { variant_records: :blob }]) }

  def self.ransackable_attributes(_auth_object = nil)
    %w[id name comment]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[product_components]
  end

  def self.with_only_components(*component_ids)
    joins(:product_components)
      .group('products.id')
      .where(product_components: { component_id: component_ids })
      .having('COUNT(DISTINCT product_components.component_id) = ?', component_ids.size)
  end

  def self.ransackable_scopes(_auth_object = nil)
    [:with_only_components]
  end

  def update_price
    # component_total = product_components.joins(:component).sum('components.price_cents * product_components.quantity')
    # self.price_cents = component_total
    base = aluminum_price_cents + glass_price_cents + other_price_cents
    self.price_cents = (base + (base * profit_percentage / 100.0)).round
    save
  end

  def total_price_cents
    price_cents * (quantity || 1)
  end

  def total_price
    Money.new(total_price_cents, currency)
  end

  def area
    width * height
  end

  def area_m2
    UnitConverter.mm2_to_m2(area)
  end

  def area_ft2
    UnitConverter.mm2_to_ft2(area)
  end

  def perimeter
    2 * (width + height)
  end

  private

  def recalculate_product_components_amount
    # We need to update the quantity of each product component and save
    product_components.each do |product_component|
      product_component.set_quantity_fields
      product_component.save
    end
  end

  def profit_percentage
    order_version&.profit.to_f
  end

  def update_order_version_total_amount
    order_version.update_total_amount
  end

  def copy_template
    template = company&.products&.find_by(id: template_id, order_version: nil)

    if template
      self.name = template.name
      self.comment = template.comment
      image.attach(template.image.blob)
      self.product_components = template.product_components.map(&:dup)
    else
      errors.add(:template_id, :not_found)
      throw :abort
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_order_version, only: %i[new create]

  # GET /products
  def index
    products = current_company.products.with_image_variants.where(order_version_id: nil).order(id: :desc)

    @search = products.ransack(params[:q])
    @pagy, @products = pagy(@search.result(distinct: true))
  end

  # GET /products/1
  def show
    @product_components = @product.product_components.includes(component: :company).group_by do |pc|
      pc.component.category
    end
  end

  # GET /products/new
  def new
    @product = Product.new(order_version_id: @order_version&.id, from_template: params[:from_template])
  end

  # GET /products/1/edit
  def edit; end

  # POST /products
  def create
    @product = Product.new(product_params)
    @product.company = current_company
    @product.order_version_id = @order_version.id if @order_version

    if @product.save
      if @order_version
        render turbo_stream: turbo_stream.update(@order_version, partial: 'order_versions/order_version',
                                                                 locals: { order_version: @product.order_version })

      else
        redirect_to @product, notice: 'Product template was successfully created.'
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product template was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy!
    if @product.order_version
      render turbo_stream: turbo_stream.update(@product.order_version,
                                               partial: 'order_versions/order_version',
                                               locals: { order_version: @product.order_version })
    else
      redirect_to products_path, notice: 'Product template was successfully destroyed.', status: :see_other
    end
  end

  private

  def set_product
    @product = current_company.products.find(params.expect(:id))
  end

  def set_order_version
    @order_version = (current_company.order_versions.find(params[:order_version_id]) if params[:order_version_id])
  end

  def product_params
    params.expect(product: %i[name width height comment image from_template template_id quantity])
  end
end

app/views/products/_product.html.erb
<div id="<%= dom_id product %>" class="flex flex-col gap">
  <div class="flex justify-center">
    <%= product.image.attached? ? image_or_placeholder(product.image, 200, 200) : "No image" %>
  </div>
  <div class="flex justify-between">
    <h4 class="font-medium leading-none">Name:</h4>
    <p class="leading-none"><%= product.name %></p>
  </div>
  <div class="flex justify-between">
    <h4 class="font-medium leading-none">Quantity:</h4>
    <p class="leading-none"><%= product.quantity %></p>
  </div>

  <div class="flex justify-between">
    <h4 class="font-medium leading-none">Width:</h4>
    <p class="leading-none"><%= UnitConverter.mm_to_m(product.width) %> m</p>
  </div>
  <div class="flex justify-between">
    <h4 class="font-medium leading-none">Height:</h4>
    <p class="leading-none"><%= UnitConverter.mm_to_m(product.height) %> m</p>
  </div>
  <div class="flex justify-between">
    <h4 class="font-medium leading-none">Area: </h4>
    <p class="leading-none"><%= product.area_m2 %> m² / <%= product.area_ft2 %> ft²</p>
  </div>
  <div class="flex justify-between">
    <h4 class="font-medium leading-none">Perimeter: </h4>
    <p class="leading-none"><%= UnitConverter.mm_to_m(product.perimeter) %> m</p>
  </div>
  <div class="flex justify-between">
    <h4 class="font-medium leading-none">Comment:</h4>
    <p class="leading-none"><%= product.comment %></p>
  </div>
  <div class="flex justify-between">
    <h4 class="font-medium leading-none">Price: </h4>
    <p class="leading-none"><%= product.price.format %></p>
  </div>
</div>

app/views/products/_product_order_row.html.erb
<tr data-controller="dialog" data-action="click->dialog#showModal" class="cursor-pointer hover:bg-gray-50 transition">
  <td><%= index+1 %></td>
  <td><%= image_or_placeholder(product.image, 100, 150) %></td>
  <td>
    <%= product.name %>
    <dialog class="dialog" data-dialog-target="menu"  style="--max-i-lg: fit-content;" data-action="click->dialog#closeOnClickOutside">
      <button type="button" class="btn btn--plain dialog__close" data-action="click->dialog#close">
        <%= image_tag "x.svg", size: 16, aria: { hidden: true } %>
        <span class="sr-only">Close</span>
      </button>
      <div class="dialog__content">
        <%= turbo_frame_tag product, src: product_path(product), loading: "lazy", data: {dialog_target: "frame"} do %>
          <div class="flex flex-col gap">
            <div class="skeleton rounded-lg" style="height: 300px; width: 300px;"></div>
          </div>
        <% end %>
      </div>
    </dialog>
  </td>
  <td><%= product.quantity %></td>
  <td><%= UnitConverter.mm_to_m(product.width) %></td>
  <td><%= UnitConverter.mm_to_m(product.height) %></td>
  <td><%= product.area_m2 %></td>
  <td><%= product.aluminum_price.format %></td>
  <td><%= product.glass_price.format %></td>
  <td><%= product.other_price.format %></td>
  <td><%= product.price.format %></td>
  <td><%= product.nett_price.format %></td>
  <td><%= product.profit_amount.format %></td>
  <td><%= product.price_with_profit.format %></td>
  <td><%= product.total_nett_price.format %></td>
  <td><%= product.total_profit_amount.format %></td>
  <td><%= product.total_price_with_profit.format %></td>
  <td>
    <%= dropdown_button(
      links: [
        { name: "Show", url: '#', data: { action: "click->dialog#show"} },
        { name: "Edit", url: edit_product_path(product), data: { action: "click->dialog#openFromLink"} },
        :separator,
        { name: "Delete", url: product, data: { turbo_method: :delete, turbo_confirm: "Are you absolutely sure?" } }
      ]
    )
    %>
  </td>
</tr>

app/views/products/_table_row.html.erb
<tr data-controller="link" data-link-href-value="<%= edit_product_path(product) %>" class="cursor-pointer hover:bg-gray-50 transition">
  <td><%= product.id %></td>
  <td><%= product.image.attached? ? image_or_placeholder(product.image, 100, 150) : "No image" %></td>
  <td><%= link_to product.name, product, data: {turbo_frame: "_top"} %></td>
  <td><%= UnitConverter.mm_to_m(product.width) %></td>
  <td><%= UnitConverter.mm_to_m(product.height) %></td>
  <td style='white-space: nowrap;'><%= product.area_m2 %></td>
  <td><%= product.comment.presence || '—' %></td>
  <td class="text-end"><%= product.price.format %></td>
  <td style='white-space: nowrap;'>
    <%= link_to "Edit", product, data: {turbo_frame: "_top"}%> |
    <%= link_to "Delete", product, data: { turbo_method: :delete, turbo_confirm: "Are you absolutely sure?" } %>
  </td>
</tr>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>
<%= turbo_frame_tag @product, target: "_top" do %>
  <h1 class="font-bold text-4xl mbe-4">Editing product</h1>
  <%= render "form", product: @product %>
<% end %>

app/views/products/index.html.erb
<% content_for :title, "Products" %>
<div id="product_templates" class="container flex flex-col">
  <div class="container flex flex-col">
    <div class="flex flex-col mbe-8">
      <div class="flex items-center justify-between">
        <div>
          <h1 class="font-bold text-4xl">Product templates</h1>
        </div>
        <%= link_to "New template", new_product_path, class: "btn btn--primary" %>
      </div>
    </div>
  </div>
  <%= search_form_for @search, class: "flex items-center justify-between gap mbe-4", data: { controller: "form" } do |form| %>
    <div class="flex items-center grow gap">
      <%= form.search_field :name_or_comment_cont_any, placeholder: "Name, comment", autocomplete: "off", class: "input", style: "max-inline-size: 250px", data: { form_target: "searchInput", action: "form#submitLater", turbo_permanent: true } %>
      <div class="container flex flex-col grow">
        <%= form.select :with_only_components, options_for_select(current_company.components.pluck(:name, :id), params.dig(:q, :with_only_components)),
  { include_blank: "Includes components...", include_hidden: false},
  { multiple: true, data: { controller: "combobox", action: "change->form#submit" } } %>
      </div>
      <%= link_to "Reset", products_path, data: { form_target: "cancel", action: "click->form#cancel" }, class: "btn btn--borderless show@md" if params.has_key?(:q)%>
    </div>
  <% end %>
</div>
<%= turbo_frame_tag :products_table do %>
  <div class="relative i-full overflow-x-auto border rounded-lg mbe-4">
    <table class="table">
      <thead>
        <tr>
          <th><%= sort_link(@search, :id, class: "flex items-center") %></th>
          <th>Image</th>
          <th><%= sort_link(@search, :name, class: "flex items-center") %></th>
          <th style='white-space: nowrap;'>Width, m</th>
          <th style='white-space: nowrap;'>Height, m</th>
          <th style='white-space: nowrap;'>Area, m²</th>
          <th>Comment</th>
          <th>Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% if @products.blank? %>
          <tr>
            <td colspan="10" class="text-center p-8">No Results.</td>
          </tr>
        <% else %>
          <%= render partial: "products/table_row", collection: @products, as: :product, cached: true  %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="flex items-center">
    <div class="text-sm text-subtle show@md">Displaying <%= @pagy.in %> of <%= @pagy.count %> record(s).</div>
    <div class="flex items-center mis-auto justify-end" style="column-gap: 1rem">
      <%= form_with url: pagy_url_for(@pagy, 1), class: "flex items-center gap show@md", method: :get, data: { controller: "form", action: "change->form#submit" } do |form| %>
        <%= form.label :limit, "Rows per page", class: "text-sm font-medium" %>
        <%= form.select :limit, [10, 20, 30, 40, 50], { selected: @pagy.limit }, { class: "input", style: "--input-inline-size: 70px" } %>
      <% end %>
      <div class="text-sm font-medium"><%= "Page #{@pagy.page} of #{@pagy.pages}" %></div>
      <nav class="flex items-center gap shrink-0" style="--btn-padding: .5rem;" aria-label="Pagination">
        <%= link_to pagy_url_for(@pagy, 1), class: "btn", aria: { disabled: @pagy.prev.nil? }.compact_blank do %>
          <%= image_tag "chevrons-left.svg", size: 16, aria: { hidden: true } %>
          <span class="sr-only">Go to first page</span>
        <% end %>
        <%= link_to pagy_url_for(@pagy, @pagy.prev || @pagy.page), class: "btn", aria: { disabled: @pagy.prev.nil? }.compact_blank do %>
          <%= image_tag "chevron-left.svg", size: 16, aria: { hidden: true } %>
          <span class="sr-only">Go to previous page</span>
        <% end %>
        <%= link_to pagy_url_for(@pagy, @pagy.next || @pagy.page), class: "btn", aria: { disabled: @pagy.next.nil? }.compact_blank do %>
          <%= image_tag "chevron-right.svg", size: 16, aria: { hidden: true } %>
          <span class="sr-only">Go to next page</span>
        <% end %>
        <%= link_to pagy_url_for(@pagy, @pagy.last), class: "btn", aria: { disabled: @pagy.next.nil? }.compact_blank do %>
          <%= image_tag "chevrons-right.svg", size: 16, aria: { hidden: true } %>
          <span class="sr-only">Go to last page</span>
        <% end %>
      </nav>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<% content_for :title, "New product" %>
<%= turbo_frame_tag(@product, @product.order_version_id, target: (@product.order_version_id.nil? ? "_top" : nil)) do %>
  <h1 class="font-bold text-4xl mbe-4">New product</h1>
  <%= render "form", product: @product %>
<% end %>

app/views/products/show.html.erb
<%= turbo_frame_tag @product, target: "_top" do %>
  <%= render "products/product", product: @product %>
  <div class="flex items-center justify-between grow mb-4 gap">
    <% if @product.order_version %>
      <div></div>
    <% else %>
      <%= link_to "Back", products_path, class: "btn btn-sm i-full", style: "width: 200px;" %>
    <% end %>
    <div class ="flex justify-end gap">
      <%= link_to "Destroy", @product, class: "btn btn-sm btn--secondary", style: "width: 100px;", data: { turbo_method: :delete, turbo_confirm: "Are you absolutely sure?" } %>
      <%= link_to "Edit", edit_product_path(@product), class: "btn btn-sm btn--primary", style: "width: 100px;" %>
    </div>
  </div>
  <div class="flex items-center gap">
    <div class="font-semibold">Aluminium</div>
    <hr class="grow mbs-1 border-dark" aria-hidden="true">
  </div>
  <table class="table" data-controller="check-all">
    <thead>
      <tr>
        <th>#</th>
        <th>Code</th>
        <th>Name</th>
        <th>Quantity</th>
        <th>Quantity manual</th>
        <th>Weight</th>
        <th>Price</th>
        <th>Amount</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "product_components/product_component", collection: @product_components['aluminum'] %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="7">Total:</td>
        <td><%= @product.aluminum_price.format %></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  <%= link_to new_product_component_path(@product), class: "btn i-full mb-4", data: {turbo_frame: "_self"} do %>
    <%= image_tag "circle-plus.svg", size: 16, aria: { hidden: true } %>
    <span>Add component</span>
  <% end %>
  <div class="flex items-center gap mb-4">
    <div class="font-semibold">Glass / filler</div>
    <hr class="grow mbs-1 border-dark" aria-hidden="true">
  </div>
  <table class="table" data-controller="check-all">
    <thead>
      <tr>
        <th>#</th>
        <th>Code</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Amount manual</th>
        <th>Weight</th>
        <th>Price</th>
        <th>Total</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "product_components/product_component", collection: @product_components['glass'] %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="7">Total:</td>
        <td><%= @product.glass_price.format %></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  <%= link_to new_product_component_path(@product), class: "btn i-full mb-4", data: {turbo_frame: "_self"} do %>
    <%= image_tag "circle-plus.svg", size: 16, aria: { hidden: true } %>
    <span>Add component</span>
  <% end %>
  <div class="flex items-center gap mb-4">
    <div class="font-semibold">Other</div>
    <hr class="grow mbs-1 border-dark" aria-hidden="true">
  </div>
  <table class="table" data-controller="check-all">
    <thead>
      <tr>
        <th>#</th>
        <th>Code</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Amount manual</th>
        <th>Weight</th>
        <th>Price</th>
        <th>Total</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "product_components/product_component", collection: @product_components['other'] %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="7">Total:</td>
        <td><%= @product.other_price.format %></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  <%= link_to new_product_component_path(@product), class: "btn i-full mb-4", data: {turbo_frame: "_self"} do %>
    <%= image_tag "circle-plus.svg", size: 16, aria: { hidden: true } %>
    <span>Add component</span>
  <% end %>
<% end %>